### ISSUE TITLE
statInt = interval * 3 # There are 3 20s samples in each minute

### ISSUE THREAD

**Issue by amoghmahesh** [lgeeklee/python-vmstats#9]
May I know what exactly does this line mean?

does it mean the output is printed after an interval of 1 minute?

if we want to see output after an timespan of 5 minutes, do we need to send 100s as interval?

Thank you

**Comment by lgeeklee** [comment]
The interval (in minutes) can be supplied at the command line - by default it's 15 minutes.
Because each sample is taken every 20s, there are 3 samples taken for the VM each minute.  
The line you mentioned above is because the data coming back has 3 times as many values (as we request - for example - 15 minutes worth of data - which is 45 samples), so it's typically divided by "StatInt" for the final value.
